import seat from "../images/seat.png";

const busDate = {
  seatPrices: ["All", "699", "899", "1199", "1599"],
  seatInfo: [
    { id: 1, value: "Vacant Seats", selected: false },
    { id: 2, value: "Reserved Seats", selected: false },
    { id: 3, value: "Selexted Seats", selected: false },
  ],
  BusList: [
    {
      id: 1,
      runningDay: ["Tuesday", "Thursday", "Saturday"],
      name: "Intercity Smart",
      seatType: ["A/C Sleeper(2+1)", "|", "Left Seat", "|", "Window Seat"],
      seatInfo: ["Live Tracking", "Policies", "Photos", "Amenities", "Review"],
      rating: "3",
      price: "$899",
      depTime: "8:30",
      arrTime: "20:30",
      timeduration: "011hrs59min",
      pickPoint: "Delhi",
      dropPoint: "Mumbai",
      depPoint: "Delhi Road",
      arrPoint: "Mumbai Road",
      busSeatData: {
        UpperSheet: {
          id: 1,
          name: "Upper Sheet",
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
        lowerSheet: {
          name: "Upper Sheet",
          id: 1,
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
      },
    },
    {
      id: 2,
      runningDay: ["Tuesday", "Thursday", "Saturday"],
      name: "Safar Exp",
      seatType: ["A/C Sleeper(2+1)", "|", "Left Seat", "|", "Window Seat"],
      seatInfo: ["Live Tracking", "Policies", "Photos", "Amenities", "Review"],
      rating: "3",
      price: "$899",
      depTime: "13:30",
      arrTime: "23:30",
      timeduration: "10hrs59min",
      pickPoint: "Delhi",
      dropPoint: "Mumbai",
      depPoint: "Delhi Road",
      arrPoint: "Mumbai Road",

      busSeatData: {
        UpperSheet: {
          id: 1,
          name: "Upper Sheet",
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
        lowerSheet: {
          name: "Upper Sheet",
          id: 1,
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
      },
    },
    {
      id: 3,
      runningDay: ["Tuesday", "Thursday", "Saturday"],
      name: "Zing Bus",
      seatType: ["A/C Sleeper(2+1)", "|", "Left Seat", "|", "Window Seat"],
      seatInfo: ["Live Tracking", "Policies", "Photos", "Amenities", "Review"],
      rating: "3",
      price: "$899",
      depTime: "22:00",
      arrTime: "10:00",
      timeduration: "11hrs59min",
      pickPoint: "Delhi",
      dropPoint: "Mumbai",
      depPoint: "Delhi Road",
      arrPoint: "Mumbai Road",

      busSeatData: {
        UpperSheet: {
          id: 1,
          name: "Upper Sheet",
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
        lowerSheet: {
          name: "Upper Sheet",
          id: 1,
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
      },
    },
    {
      id: 4,
      runningDay: ["Tuesday", "Thursday", "Saturday"],
      name: "Zing Bus",
      seatType: ["A/C Sleeper(2+1)", "|", "Left Seat", "|", "Window Seat"],
      seatInfo: ["Live Tracking", "Policies", "Photos", "Amenities", "Review"],
      rating: "4.5",
      price: "$899",
      depTime: "22:45",
      arrTime: "06:20",
      timeduration: "07hrs59min",
      pickPoint: "Mumbai",
      dropPoint: "Delhi",
      depPoint: "Mumbai Road",
      arrPoint: "Delhi Road",

      busSeatData: {
        UpperSheet: {
          id: 1,
          name: "Upper Sheet",
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
        lowerSheet: {
          name: "Upper Sheet",
          id: 1,
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
      },
    },
    {
      id: 5,
      runningDay: ["Tuesday", "Thursday", "Saturday"],
      name: "Safar Exp",
      seatType: ["A/C Sleeper(2+1)", "|", "Left Seat", "|", "Window Seat"],
      seatInfo: ["Live Tracking", "Policies", "Photos", "Amenities", "Review"],
      rating: "2.8",
      price: "$899",
      depTime: "22:45",
      arrTime: "06:20",
      timeduration: "07hrs59min",
      pickPoint: "Mumbai",
      dropPoint: "Hedrabad",
      depPoint: "Mumbai Road",
      arrPoint: "Hedrabad Road",

      busSeatData: {
        UpperSheet: {
          id: 1,
          name: "Upper Sheet",
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
        lowerSheet: {
          name: "Upper Sheet",
          id: 1,
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
      },
    },
    {
      id: 6,
      name: "Intercity Smart",
      runningDay: ["Monday", "Wednesday", "Friday", "Sunday"],
      seatType: ["A/C Sleeper(2+1)", "|", "Left Seat", "|", "Window Seat"],
      seatInfo: ["Live Tracking", "Policies", "Photos", "Amenities", "Review"],
      rating: "4",
      price: "$899",
      depTime: "22:45",
      arrTime: "06:20",
      timeduration: "07hrs59min",
      pickPoint: "Hedrabad",
      dropPoint: "Mumbai",
      depPoint: "Hedrabad Road",
      arrPoint: "Mumbai Road",

      busSeatData: {
        UpperSheet: {
          id: 1,
          name: "Upper Sheet",
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
        lowerSheet: {
          name: "Upper Sheet",
          id: 1,
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
      },
    },
    {
      id: 7,
      runningDay: ["Tuesday", "Thursday", "Saturday"],
      name: "Zing Bus",
      seatType: ["A/C Sleeper(2+1)", "|", "Left Seat", "|", "Window Seat"],
      seatInfo: ["Live Tracking", "Policies", "Photos", "Amenities", "Review"],
      rating: "2.5",
      price: "$899",
      depTime: "22:45",
      arrTime: "06:20",
      timeduration: "07hrs59min",
      pickPoint: "Delhi",
      dropPoint: "Hedrabad",
      depPoint: "Delhi Road",
      arrPoint: "Hedrabad Road",

      busSeatData: {
        UpperSheet: {
          id: 1,
          name: "Upper Sheet",
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
        lowerSheet: {
          name: "Upper Sheet",
          id: 1,
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
      },
    },
    {
      id: 8,
      runningDay: ["Monday", "Wednesday", "Friday", "Sunday"],
      name: "Safar Exp",
      seatType: ["A/C Sleeper(2+1)", "|", "Left Seat", "|", "Window Seat"],
      seatInfo: ["Live Tracking", "Policies", "Photos", "Amenities", "Review"],
      rating: "3",
      price: "$899",
      depTime: "22:45",
      arrTime: "06:20",
      timeduration: "07hrs59min",
      pickPoint: "Hedrabad",
      dropPoint: "Delhi",
      depPoint: "Hedrabad Road",
      arrPoint: "Delhi Road",

      busSeatData: {
        UpperSheet: {
          id: 1,
          name: "Upper Sheet",
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
        lowerSheet: {
          name: "Upper Sheet",
          id: 1,
          seatLeft: [
            { id: 1, price: "599", value: seat, selected: false },
            { id: 2, price: "699", value: seat, selected: false },
            { id: 3, price: "799", value: seat, selected: false },
            { id: 4, price: "899", value: seat, selected: false },
            { id: 5, price: "799", value: seat, selected: false },
            { id: 6, price: "699", value: seat, selected: false },
            { id: 7, price: "599", value: seat, selected: false },
          ],
          seatMid: [
            { id: 8, price: "599", value: seat, selected: false },
            { id: 9, price: "699", value: seat, selected: false },
            { id: 10, price: "799", value: seat, selected: false },
            { id: 11, price: "899", value: seat, selected: false },
            { id: 12, price: "799", value: seat, selected: false },
            { id: 13, price: "699", value: seat, selected: false },
            { id: 14, price: "599", value: seat, selected: false },
          ],
          seatRight: [
            { id: 15, price: "599", value: seat, selected: false },
            { id: 16, price: "699", value: seat, selected: false },
            { id: 17, price: "799", value: seat, selected: false },
            { id: 18, price: "899", value: seat, selected: false },
            { id: 19, price: "799", value: seat, selected: false },
          ],
        },
      },
    },
  ],
};

export default busDate;
