const actionTypes = {

    INITIALIZE: 'INITIALIZE',
    BUSDETAIL_API_SUCCESS: 'BUSDETAIL_API_SUCCESS',
    BUSDETAIL_API_ERROR: 'BUSDETAIL_API_ERROR',

    LOCTION_SUCCESS: 'LOCTION_SUCCESS',
    LOCATION_ERROR: 'LOCATION_ERROR',

    SEATNUMBER_SUCCESS: 'SEATNUMBER_SUCCESS',
    SEATNUMBER_ERROR: 'SEATNUMBER_ERROR',

    SINGLBUSDETAIL_SUCCESS: 'SINGLBUSDETAIL_SUCCESS',
    SINGLBUSDETAIL_ERROR: 'SINGLBUSDETAIL_ERROR',

    SETPRICE_SUCCESS: 'SETPRICE_SUCCESS',
    SETPRICE_ERROR: 'SETPRICE_ERROR',

    FORM_SUCCESS: 'FORM_SUCCESS',
    FORM_ERROR: 'FORM_ERROR',

    SELECTED_BUS_SUCCESS: 'SELECTED_BUS_SUCCESS',
    SELECTED_BUS_ERROR: 'SELECTED_BUS_ERROR',
}

export default actionTypes